// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsgnxdofwaakglonufcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZ254ZG9md2Fha2dsb251ZmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTgxNDUsImV4cCI6MjA2Mjg3NDE0NX0.T4AE-RrEP-9MgT1cY8ZQz5bvDmVhF6qkvTLSiE5Kg4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);